steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/malay2sql', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malay2sql']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'  # Changed to beta
    - 'run'
    - 'deploy'
    - 'malay2sql'
    - '--image'
    - 'gcr.io/$PROJECT_ID/malay2sql'
    - '--region'
    - 'asia-southeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '8Gi'
    - '--cpu'
    - '4'
    - '--gpu'  # GPU flags now supported in beta
    - '--accelerator'
    - 'count=1,type=nvidia-tesla-t4'
    - '--set-env-vars'
    - 'OPENAI_API_KEY=${_OPENAI_API_KEY},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_DB=${_REDIS_DB}'

images:
  - 'gcr.io/$PROJECT_ID/malay2sql'

substitutions:
  _OPENAI_API_KEY: ''
  _REDIS_HOST: 'redis'
  _REDIS_PORT: '6379'
  _REDIS_DB: '0'

options:
  logging: CLOUD_LOGGING_ONLY