steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/malay2sql', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malay2sql']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'malay2sql'
    - '--image'
    - 'gcr.io/$PROJECT_ID/malay2sql'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-southeast1'
    - '--allow-unauthenticated'
    - '--memory'
    - '16Gi'
    - '--cpu'
    - '4'
    - '--timeout'
    - '600s'
    - '--execution-environment'
    - 'gen2'
    - '--gpu'
    - '1'
    - '--gpu-type'
    - 'nvidia-l4'
    - '--no-cpu-throttling'
    - '--max-instances'
    - '1'
    - '--port'
    - '8080'
    - '--set-env-vars'
    - 'OPENAI_API_KEY=${_OPENAI_API_KEY},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_DB=${_REDIS_DB}'

images:
  - 'gcr.io/$PROJECT_ID/malay2sql'

substitutions:
  _OPENAI_API_KEY: ''
  _REDIS_HOST: 'redis'
  _REDIS_PORT: '6379'
  _REDIS_DB: '0'

options:
  logging: CLOUD_LOGGING_ONLY