steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/malay2sql'
      - '--memory'
      - '32g'  # Increase Docker build memory
      - '--memory-swap'
      - '32g'
      - '.'
    timeout: '3600s'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malay2sql']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'malay2sql'
    - '--image'
    - 'gcr.io/$PROJECT_ID/malay2sql'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-southeast1'
    - '--allow-unauthenticated'
    - '--memory'
    - '16Gi'
    - '--cpu'
    - '4'
    - '--timeout'
    - '1200s'
    - '--execution-environment'
    - 'gen2'
    - '--gpu'
    - '1'
    - '--gpu-type'
    - 'nvidia-l4'
    - '--no-cpu-throttling'
    - '--max-instances'
    - '1'
    - '--port'
    - '8080'
    - '--set-env-vars'
    - 'OPENAI_API_KEY=${_OPENAI_API_KEY},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_DB=${_REDIS_DB},DATABASE_URL=postgresql://malay2sql-user:${_DB_PASSWORD}@localhost/malay2sql?host=/cloudsql/${PROJECT_ID}:asia-southeast1:malay2sql-db'
    - '--set-cloudsql-instances'
    - '${PROJECT_ID}:asia-southeast1:malay2sql-db'

substitutions:
  _OPENAI_API_KEY: ''
  _REDIS_HOST: 'redis'
  _REDIS_PORT: '6379'
  _REDIS_DB: '0'
  _DB_PASSWORD: ''

options:
  machineType: 'N1_HIGHCPU_32'  # Use a machine with more memory
  logging: CLOUD_LOGGING_ONLY
