steps:
  # Decrypt secrets if needed
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.prod.enc
      - --plaintext-file=.env.prod
      - --location=global
      - --keyring=my-keyring
      - --key=my-key

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/malay2sql', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malay2sql']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'malay2sql'
    - '--image'
    - 'gcr.io/$PROJECT_ID/malay2sql'
    - '--region'
    - 'asia-southeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '8Gi'
    - '--cpu'
    - '4'
    - '--gpu'
    - '--accelerator=count=1,type=nvidia-tesla-t4'
    - '--set-env-vars'
    - 'REDIS_HOST=redis,REDIS_PORT=6379,REDIS_DB=0'
    - '--set-secrets'
    - 'OPENAI_API_KEY=openai-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/malay2sql'