name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    # Create .env.prod file from secrets
    - name: Create env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env.prod
        echo "REDIS_HOST=redis" >> .env.prod
        echo "REDIS_PORT=6379" >> .env.prod
        echo "REDIS_DB=0" >> .env.prod

    - name: Deploy to Cloud Run
      run: |
        gcloud builds submit --config cloudbuild.yaml