version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models/translator
      - RERANKER_PATH=/app/models/reranker
    volumes:
      - ./models:/app/models  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis
      - db

  redis:
    image: redis:6
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=malay2sql-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=malay2sql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: