name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Create env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env.prod
        echo "REDIS_HOST=redis" >> .env.prod
        echo "REDIS_PORT=6379" >> .env.prod
        echo "REDIS_DB=0" >> .env.prod

    - name: Deploy to Cloud Run
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        gcloud builds submit --config cloudbuild.yaml \
          --substitutions=_OPENAI_API_KEY="$OPENAI_API_KEY",_REDIS_HOST="redis",_REDIS_PORT="6379",_REDIS_DB="0"